export const POSTS = [
  {
    slug: "reduce-claim-denials",
    category: "Denial Management",
    categoryColor: "#E8F4FF",
    categoryText: "#111111",
    title: "7 proven ways to reduce claim denials in your practice",
    excerpt: "Claim denials cost US medical practices billions every year. Here are the most effective strategies our billing specialists use to prevent denials before they happen.",
    date: "June 5, 2025",
    readTime: "6 min read",
    emoji: "🚫",
    bg: "linear-gradient(135deg,#F0EBE0 0%,#E8F7F5 100%)",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80&fit=crop",
  },
  {
    slug: "medical-billing-2025",
    category: "Industry News",
    categoryColor: "#FFF4E8",
    categoryText: "#C47A00",
    title: "Medical billing changes to know about in 2025",
    excerpt: "From updated ICD-10 codes to new Medicare reimbursement rules, here's what every practice manager needs to know heading into 2025.",
    date: "May 28, 2025",
    readTime: "5 min read",
    emoji: "📰",
    bg: "linear-gradient(135deg,#FFF8EE 0%,#FFF4E0 100%)",
    image: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=600&q=80&fit=crop",
  },
  {
    slug: "ar-days-improvement",
    category: "Revenue Cycle",
    categoryColor: "#E8F9F4",
    categoryText: "#00875A",
    title: "How to get your AR days under 30 — and keep them there",
    excerpt: "High AR days mean cash flow problems. We break down the exact strategies MedCare uses to consistently keep client AR days below 30.",
    date: "May 14, 2025",
    readTime: "8 min read",
    emoji: "📈",
    bg: "linear-gradient(135deg,#E8F9F4 0%,#EAF7FF 100%)",
    image: "https://images.unsplash.com/photo-1543286386-713bdd548da4?w=600&q=80&fit=crop",
  },
  {
    slug: "credentialing-mistakes",
    category: "Credentialing",
    categoryColor: "#F3E8FF",
    categoryText: "#7C3AED",
    title: "5 credentialing mistakes that delay your revenue",
    excerpt: "Credentialing errors can delay a provider's billing by weeks or months. Learn the most common mistakes and how to avoid them.",
    date: "April 30, 2025",
    readTime: "5 min read",
    emoji: "🪪",
    bg: "linear-gradient(135deg,#F3E8FF 0%,#F0EBE0 100%)",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&q=80&fit=crop",
  },
  {
    slug: "patient-billing-collections",
    category: "Patient Billing",
    categoryColor: "#FFE8F0",
    categoryText: "#C0185B",
    title: "Improving patient collections without damaging relationships",
    excerpt: "Collecting patient balances is one of the hardest parts of running a practice. Here's how to do it effectively while preserving trust.",
    date: "April 18, 2025",
    readTime: "7 min read",
    emoji: "👤",
    bg: "linear-gradient(135deg,#FFE8F0 0%,#FFF0F5 100%)",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVmy5PlZ3EfWub5s7wctZaZfNQhaF35yVvNsjBzn88dQ&s=10&fit=crop",
  },
  {
    slug: "rcm-technology-2025",
    category: "Technology",
    categoryColor: "#E8FFF0",
    categoryText: "#00875A",
    title: "The RCM technology stack every modern practice should consider",
    excerpt: "From AI-powered claim scrubbing to automated eligibility verification, we break down the tools transforming revenue cycle management.",
    date: "April 5, 2025",
    readTime: "6 min read",
    emoji: "💻",
    bg: "linear-gradient(135deg,#E8FFF0 0%,#F0EBE0 100%)",
    image: "https://truecarercm.com/wp-content/uploads/2025/10/Revenue-Cycle-Management-Service-TrueCare-RCM.jpg",
  },
  {
    slug: "hipaa-compliance-guide",
    category: "Compliance",
    categoryColor: "#E8F4FF",
    categoryText: "#111111",
    title: "The complete HIPAA compliance guide for medical billing teams",
    excerpt: "HIPAA violations can cost your practice hundreds of thousands of dollars. This guide covers everything your billing team needs to stay compliant in 2025.",
    date: "March 28, 2025",
    readTime: "9 min read",
    emoji: "🔒",
    bg: "linear-gradient(135deg,#F0EBE0 0%,#F5E6A3 100%)",
    image: "https://img.economist.com.na/2024/08/mr-cc-mva-627x243.jpg",
  },
  {
    slug: "telehealth-billing",
    category: "Industry News",
    categoryColor: "#FFF4E8",
    categoryText: "#C47A00",
    title: "Telehealth billing in 2025: what's changed and what to watch",
    excerpt: "Telehealth reimbursement rules have shifted dramatically since 2020. Here's your up-to-date guide to billing virtual visits correctly and getting paid every time.",
    date: "March 15, 2025",
    readTime: "7 min read",
    emoji: "📱",
    bg: "linear-gradient(135deg,#FFF8EE 0%,#F0FAFF 100%)",
    image: "https://www.carecredit.com/sites/cc/image/what-is-telehealth.jpg",
  },
  {
    slug: "mental-health-billing",
    category: "Specialty Billing",
    categoryColor: "#F0E8FF",
    categoryText: "#6B21A8",
    title: "Mental health billing: navigating payer complexities with confidence",
    excerpt: "Mental health billing comes with unique coding challenges and payer rules. Our specialists break down how to maximize reimbursements for therapy and psychiatric services.",
    date: "March 3, 2025",
    readTime: "6 min read",
    emoji: "🧠",
    bg: "linear-gradient(135deg,#E8F9FF 0%,#F0EBE0 100%)",
    image: "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?w=600&q=80&fit=crop",
  },
  {
    slug: "outsource-medical-billing",
    category: "Revenue Cycle",
    categoryColor: "#E8F9F4",
    categoryText: "#00875A",
    title: "In-house vs outsourced billing: which is right for your practice?",
    excerpt: "Should you keep billing in-house or hand it to experts? We break down the real costs, benefits, and hidden risks of both options so you can make the right call.",
    date: "February 20, 2025",
    readTime: "8 min read",
    emoji: "⚖️",
    bg: "linear-gradient(135deg,#E8F9F4 0%,#FFF8EE 100%)",
    image: "https://images.unsplash.com/photo-1533227268428-f9ed0900fb3b?w=600&q=80&fit=crop",
  },
  {
    slug: "icd-10-coding-tips",
    category: "Coding",
    categoryColor: "#FFF0E8",
    categoryText: "#B45309",
    title: "ICD-10 coding tips that directly increase your reimbursement rate",
    excerpt: "The difference between a paid and denied claim often comes down to a single digit in your ICD-10 code. Here are the coding best practices our team swears by.",
    date: "February 8, 2025",
    readTime: "5 min read",
    emoji: "🧾",
    bg: "linear-gradient(135deg,#FFF0E8 0%,#FFF8EE 100%)",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&q=80&fit=crop",
  },
  {
    slug: "revenue-cycle-kpis",
    category: "Analytics",
    categoryColor: "#E8FFF0",
    categoryText: "#00875A",
    title: "10 revenue cycle KPIs every practice manager must track",
    excerpt: "If you're not tracking the right KPIs, you're flying blind. These 10 metrics tell you exactly how healthy your revenue cycle is — and where to fix it fast.",
    date: "January 25, 2025",
    readTime: "7 min read",
    emoji: "📊",
    bg: "linear-gradient(135deg,#E8FFF0 0%,#F0EBE0 100%)",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80&fit=crop",
  },
  {
    slug: "patient-eligibility-verification",
    category: "Revenue Cycle",
    categoryColor: "#E8F9F4",
    categoryText: "#00875A",
    title: "Why eligibility verification is your first line of defense against denials",
    excerpt: "Nearly a quarter of all denials trace back to eligibility issues caught too late. Here's how to verify coverage before the patient even sits in the waiting room.",
    date: "July 2, 2025",
    readTime: "6 min read",
    emoji: "🪪",
    bg: "linear-gradient(135deg,#E8F9F4 0%,#F0EBE0 100%)",
    image: "https://rhinomds.com/wp-content/uploads/2024/03/The-Importance-of-Eligibility-Verification-in-Healthcare-Revenue-Cycle-Management-1-1536x960-1-1024x640.webp",
  },
  {
    slug: "appeal-letter-templates",
    category: "Denial Management",
    categoryColor: "#E8F4FF",
    categoryText: "#111111",
    title: "How to write an appeal letter that actually gets claims overturned",
    excerpt: "Most appeal letters get rejected because they restate the claim instead of arguing it. Here's the structure our team uses to win first-level appeals.",
    date: "July 14, 2025",
    readTime: "7 min read",
    emoji: "✉️",
    bg: "linear-gradient(135deg,#E8F4FF 0%,#F0EBE0 100%)",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&q=80&fit=crop",
  },
  {
    slug: "small-practice-billing-mistakes",
    category: "Revenue Cycle",
    categoryColor: "#E8F9F4",
    categoryText: "#00875A",
    title: "The 6 billing mistakes that quietly drain small practice revenue",
    excerpt: "Small practices lose more to silent leaks than to outright denials. We walk through the most common — and most fixable — gaps we find during audits.",
    date: "July 22, 2025",
    readTime: "6 min read",
    emoji: "🩹",
    bg: "linear-gradient(135deg,#FFE8F0 0%,#F0EBE0 100%)",
    image: "https://www.xevensolutions.com/images/2024/08/Top-10-Medical-Billing-Errors-and-How-to-Avoid-Them.webp",
  },
  {
    slug: "prior-authorization-workflow",
    category: "Specialty Billing",
    categoryColor: "#F0E8FF",
    categoryText: "#6B21A8",
    title: "Building a prior authorization workflow that doesn't slow your practice down",
    excerpt: "Prior auth delays are one of the top causes of patient drop-off and denied claims. Here's how to build a tracking system that catches expirations before they cost you.",
    date: "August 1, 2025",
    readTime: "7 min read",
    emoji: "📋",
    bg: "linear-gradient(135deg,#F0E8FF 0%,#F0EBE0 100%)",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjS3wFy6WsfzRXnnum4BqkU1KO3Oq8GvLFMFUAjJ4_YQ&s=10",
  },
  {
    slug: "denial-trend-reporting",
    category: "Analytics",
    categoryColor: "#E8FFF0",
    categoryText: "#00875A",
    title: "Turning denial data into a roadmap for fewer denials next quarter",
    excerpt: "A denial report only matters if someone acts on it. Here's how we use monthly denial trend data to fix root causes instead of just resubmitting claims.",
    date: "August 12, 2025",
    readTime: "6 min read",
    emoji: "📉",
    bg: "linear-gradient(135deg,#E8FFF0 0%,#FFF8EE 100%)",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6xIuQKdTBLgN1R7N9iCQKN_WlJxtuKriQzN13Q5WjeA&s=10",
  },
  {
    slug: "medicare-advantage-billing",
    category: "Compliance",
    categoryColor: "#E8F4FF",
    categoryText: "#111111",
    title: "Medicare Advantage billing: what's different and why it trips up practices",
    excerpt: "MA plans don't follow traditional Medicare rules. Prior auth requirements, network restrictions, and appeal timelines all change — here's what to watch for.",
    date: "August 20, 2025",
    readTime: "8 min read",
    emoji: "🏥",
    bg: "linear-gradient(135deg,#F0EBE0 0%,#F5E6A3 100%)",
    image: "https://cdn.prod.website-files.com/66a92da624c40491a94fbb00/683f07fa9cb088511e4eb247_medicare-advantage-billing.png",
  },
];
